"""Compatibility imports for calendar consumers.

Calendar operations live in cohesive service modules; this module preserves the
established import surface without duplicating implementations or state.
"""

from services.calendar_constants import (
    ALL_DAY_EVENT_REMINDERS,
    CALENDAR_SHARE_CODE_CHARS,
    CALENDAR_SHARE_CODE_LENGTH,
    CALENDAR_SHARE_DATE_SCOPES,
    CALENDAR_SHARE_MAX_ROLLING_DAYS,
    CALENDAR_SHARE_MIN_ROLLING_DAYS,
    CANVAS_ALLOWED_ITEM_TYPES,
    CANVAS_BATCH_BYTES_LIMIT,
    CANVAS_BATCH_ITEM_LIMIT,
    CANVAS_CALENDAR_HOST_PREFIX,
    CANVAS_CALENDAR_HOST_SUFFIX,
    CANVAS_CALENDAR_PATH_PREFIXES,
    CANVAS_COMPLETION_SOURCES,
    CANVAS_COMPLETION_STATUSES,
    CANVAS_CREDENTIAL_KEYS,
    CANVAS_IDEMPOTENCY_PATTERN,
    CANVAS_LEASE_MINUTES,
    CANVAS_MIRROR_SCOPE,
    CANVAS_MIRROR_STATES,
    CANVAS_PERSONAL_EVENTS_WRITE_SCOPE,
    CANVAS_PLANNER_ITEMS_WRITE_SCOPE,
    CANVAS_PROJECTION_SCOPES,
    CANVAS_PROVIDER,
    CANVAS_READ_SCOPES,
    CANVAS_REJECTED_ITEM_TYPES,
    CANVAS_ROUTE_STATES,
    CANVAS_RUN_ID_PATTERN,
    CANVAS_SAFE_ID_PATTERN,
    CANVAS_SCOPE_ARRAY_KEYS,
    CANVAS_SCOPE_DATE_KEYS,
    CANVAS_SELECTED_MIRROR_SCOPE,
    CANVAS_SHARES_SCOPE,
    CANVAS_SOURCE_ID,
    CANVAS_SOURCE_REF_PATTERN,
    CANVAS_SOURCE_STATUSES,
    CANVAS_SYNC_TERMINAL_STATES,
    CANVAS_WRITEBACK_CREATE_STATES,
    CANVAS_WRITEBACK_SCOPE,
    CANVAS_WRITEBACK_SCOPES,
    CANVAS_WRITEBACK_STATES,
    DEFAULT_CALENDAR_COLOR,
    DEFAULT_LOCAL_SOURCE_ID,
    DEFAULT_LOCAL_SOURCE_NAME,
    FEED_SOURCE_PREFIX,
    LOCAL_SOURCE_PREFIX,
    PREFERENCES_BATCH_LIMIT,
    SIMULATED_CALENDAR_NAME,
    TIMED_EVENT_REMINDERS,
)
from services.calendar_feed_sources import (
    _configured_feed_sources,
    _configured_feed_urls,
    _delete_cache_rows_for_feed,
    _feed_needs_initial_fetch,
    _filter_configured_cache_events,
    _initial_fetch_feed_urls,
    _load_calendar_feed_metadata,
    _normalize_canvas_calendar_url,
    _refresh_initial_feed_cache,
    _resolve_last_fetched,
    _settings_payload_for_source_update,
    _validate_other_calendar_urls,
)
from services.calendar_identity import (
    _calendar_preference_unchanged,
    _calendar_preference_updates,
    _canonical_feed_url,
    _canvas_truthy,
    _default_reminder_minutes,
    _event_ref_for_cache_event,
    _event_ref_for_user_event,
    _feed_source_id,
    _feed_url_hash,
    _legacy_feed_source_id,
    _normalize_calendar_id,
    _normalize_color,
    _normalize_display_name,
    _normalize_reminder_minutes,
    _normalize_source_label,
    _raw_feed_url_hash,
    _serialized_reminder_minutes,
    _source_id_for_feed_url,
    _url_fallback_label,
)
from services.calendar_projection import (
    _load_serialized_calendar_events,
    load_events_payload_with_initial_refresh,
)
from services.calendar_serialization import (
    _api_event_overlaps_range,
    _apply_event_override,
    _coerce_utc,
    _event_overlaps_range,
    _parse_range_param,
    _range_queries,
    _serialize_canvas_event,
    _serialize_datetime,
    _serialize_event,
    _serialize_user_event,
    _span_metadata,
)
from services.calendar_shares import (
    _calendar_share_payload,
    _calendar_share_scope_label,
    _calendar_share_scope_range,
    _calendar_shares_collection,
    _fixed_end_display_date,
    _generate_calendar_share_code,
    _intersect_ranges,
    _normalize_calendar_share_payload,
    _normalize_share_calendar_ids,
    _parse_date_start,
    _parse_json_list,
    _public_calendar_events_payload,
    _public_calendar_share_context,
    _resolve_calendar_share_by_code,
    _sanitize_public_event,
    _sanitize_public_sources,
    _share_url,
)
from services.calendar_sources import (
    _append_task_calendar_source,
    _configured_calendar_sources,
    _configured_local_sources,
    _ensure_local_calendar_source,
    _ensure_user_settings,
    _load_calendar_preferences,
    _load_event_overrides,
    _load_local_calendar_sources,
    _task_calendar_payload,
    _update_local_calendar_source_payload,
    _update_url_calendar_source_payload,
    _upsert_calendar_preference,
    _upsert_event_override,
    extension_calendar_destinations,
)
from services.canvas_domain import (
    _canvas_batch_payload,
    _canvas_completion,
    _canvas_completion_source,
    _canvas_decode_json,
    _canvas_generation,
    _canvas_hash,
    _canvas_id,
    _canvas_idempotency_key,
    _canvas_item_type,
    _canvas_json,
    _canvas_link_payload,
    _canvas_normalized_value,
    _canvas_now,
    _canvas_optional_id,
    _canvas_reject_credentials,
    _canvas_result_error,
    _canvas_scope_matches,
    _canvas_source_account,
    _canvas_source_item_key,
    _canvas_source_ref,
    _canvas_source_reference,
    _canvas_sync_run_payload,
    _canvas_text,
    _canvas_timestamp,
    _canvas_user_id,
    _canvas_writeback_payload,
    _normalize_canvas_scope,
    canvas_event_ref_for_item,
    normalize_canvas_origin,
)
from services.canvas_routing import (
    _canvas_route_state,
    _canvas_routed_calendar_id,
    _load_active_canvas_sources,
    _load_canvas_import_routing_rows,
    _project_canvas_calendar_events,
    _visible_calendar_fallback,
    get_canvas_import_routing,
    set_canvas_import_routing,
)
from services.canvas_sources import (
    _archive_canvas_source_in_connection,
    _canvas_consent_from_connection,
    _canvas_routing_payload,
    _canvas_source_consent,
    _canvas_source_internal_payload,
    _canvas_source_payload,
    _canvas_source_row,
    _require_canvas_source,
    archive_canvas_import_source,
    canvas_consent_status,
    canvas_purge_preflight,
    get_canvas_import_source,
    get_canvas_import_source_context,
    list_canvas_import_sources,
    register_canvas_import_source,
    revoke_canvas_consent_in_connection,
)
from services.canvas_sync_ingestion import (
    _CANVAS_CACHE_OWNED_FIELDS,
    _canvas_bool,
    _canvas_cache_is_changed,
    _canvas_cache_row,
    _canvas_cache_values,
    _canvas_insert_cache,
    _canvas_item_value,
    _canvas_parse_batch_request,
    _canvas_update_cache,
    _normalize_canvas_item,
    ingest_canvas_sync_batch,
)
from services.canvas_sync_runs import (
    _canvas_current_generation,
    _canvas_finalize_status,
    _canvas_mark_run_expired,
    _canvas_parse_run_request,
    _canvas_run_row,
    _canvas_update_source_after_run,
    _require_current_active_run,
    begin_canvas_sync_run,
    cancel_canvas_sync_run,
    finalize_canvas_sync_run,
    get_canvas_sync_run,
    renew_canvas_sync_run,
    resume_canvas_sync_run,
)
from services.canvas_writeback import (
    _canvas_event_link_identity,
    _canvas_event_link_lookup,
    _canvas_writeback_request,
    create_canvas_event_link,
    create_canvas_event_link_result,
    create_canvas_writeback,
    create_canvas_writeback_result,
    get_canvas_event_link,
    get_canvas_writeback_result,
    list_canvas_writebacks,
    record_canvas_event_link_result,
    record_canvas_writeback_result,
)

# Shared normalization/defaults remain part of the established import surface.
from services.calendar_urls import (
    MAX_OTHER_CALENDAR_URLS,
    iter_valid_other_calendar_urls,
    load_other_calendar_urls,
    normalize_calendar_url as _normalize_calendar_url,
)
from services.settings_defaults import settings_defaults as _settings_defaults
from appwrite_helpers import parse_datetime
from services.extension_contract import extension_capability_enabled
