import assert from 'node:assert/strict';
import test from 'node:test';
import { adminPanelRuntime, response, sectionHtml, settle } from './helpers/admin-panel.mjs';

const term = { term: 'Fall_2026', label: 'Fall 2026', state: 'upcoming', effective_state: 'upcoming', revision: 7, catalog_available: true };
const body = (request) => JSON.parse(request.options.body);
const invalidJson = () => ({ ok: true, status: 200, headers: { get: () => 'text/html' }, json: async () => { throw new SyntaxError('Unexpected login HTML'); } });

async function tracking() {
  const fixture = await adminPanelRuntime();
  assert.equal(fixture.requests[0].url, 'https://example.test/admin/auth/sections/course-tracking');
  assert.equal(fixture.requests[0].options.headers.Accept, 'text/html');
  await fixture.loadTracking();
  fixture.requests[1].resolve(response({ terms: [term] }));
  await settle();
  return fixture;
}

test('tracking group and row controls reload the actual auth panel and bind each replacement once', async () => {
  const fixture = await tracking();
  const { panel, window, requests, timers, document } = fixture;
  window.initAdminCourseTracking(panel);
  window.initAdminCourseTracking(panel);
  assert.equal(timers.size, 1);
  const group = panel.querySelector('[data-group-toggle]');
  fixture.emit(group, 'click');
  assert.equal(requests.length, 3, 'reinitialization must not duplicate mutation listeners');
  assert.equal(group.disabled, true);
  assert.equal(requests[2].url, '/admin/course-tracking/groups/toggle');
  assert.deepEqual(body(requests[2]), { term: 'Fall_2026', subject: 'CS', catalog: '170', crn: '12345', enabled: true });
  assert.equal(requests[2].options.headers['X-CSRFToken'], 'fixture-csrf');
  assert.equal(requests[2].options.credentials, 'same-origin');
  requests[2].resolve(response({ success: true }));
  await settle();
  assert.equal(requests[3].url, 'https://example.test/admin/auth/sections/course-tracking');
  assert.equal(document.getElementById('admin-auth-shell').attributes['aria-busy'], 'true');
  await fixture.loadTracking('group-updated');
  requests[4].resolve(response({ terms: [term] }));
  await settle();
  assert.equal(panel.querySelector('[data-section-version]').dataset.sectionVersion, 'group-updated');
  assert.equal(document.getElementById('admin-auth-shell').attributes['aria-busy'], 'false');
  assert.equal(timers.size, 1, 'replacement clears the prior refresh timer');
  const row = panel.querySelector('[data-track-toggle]');
  fixture.emit(row, 'click');
  assert.equal(requests.length, 6);
  assert.equal(requests[5].url, '/admin/course-tracking/tracks/track%2F17/toggle');
  assert.deepEqual(body(requests[5]), { enabled: false });
  requests[5].resolve(response({ success: true }));
  await settle();
  await fixture.loadTracking('row-updated');
  requests.at(-1).resolve(response({ terms: [term] }));
  await settle();
  assert.equal(panel.querySelector('[data-section-version]').dataset.sectionVersion, 'row-updated');
  assert.deepEqual(fixture.notices.map(({ message }) => message), ['Course tracking group resumed.', 'Course tracking row paused.']);
});

test('invalid HTML, conflict and rejected tracking mutations retain retry controls without a false reload', async () => {
  const fixture = await tracking();
  const { panel, requests, notices } = fixture;
  const group = panel.querySelector('[data-group-toggle]');
  fixture.emit(group, 'click');
  requests[2].resolve(invalidJson());
  await settle();
  assert.equal(requests.length, 3);
  assert.equal(group.disabled, false);
  assert.equal(notices.at(-1).message, 'Invalid JSON response.');
  assert.equal(notices.at(-1).type, 'error');
  const decodeError = fixture.errors.at(-1)[1];
  assert.equal(decodeError.status, 200);
  assert.equal(decodeError.cause.message, 'Unexpected login HTML');
  const row = panel.querySelector('[data-track-toggle]');
  fixture.emit(row, 'click');
  requests[3].resolve(response({ message: 'Tracking changed by another admin. Retry.', error: 'Lower-priority code' }, 409));
  await settle();
  assert.equal(row.disabled, false);
  assert.equal(requests.length, 4);
  assert.equal(notices.at(-1).message, 'Tracking changed by another admin. Retry.');
  assert.equal(fixture.errors.at(-1)[1].status, 409);
  fixture.emit(row, 'click');
  requests[4].reject(new Error('Connection interrupted'));
  await settle();
  assert.equal(row.disabled, false);
  assert.equal(requests.length, 5);
  assert.equal(notices.at(-1).message, 'Connection interrupted');
  assert.ok(notices.every(({ type }) => type === 'error'));
});

test('refresh controls roll back failures, accept saved intervals, and trigger real reloads from the live timer', async () => {
  const fixture = await tracking();
  const { panel, requests, notices, timers, window } = fixture;
  const select = panel.querySelector('#admin-tracking-refresh');
  window.initAdminCourseTracking(panel);
  select.value = '10';
  fixture.emit(select, 'change');
  assert.equal(requests.length, 3);
  assert.deepEqual(body(requests[2]), { minutes: 10 });
  requests[2].resolve(invalidJson());
  await settle();
  assert.equal(select.value, '5');
  assert.equal([...timers.values()][0].ms, 5 * 60 * 1000);
  assert.equal(notices.at(-1).type, 'error');
  select.value = '10';
  fixture.emit(select, 'change');
  requests[3].resolve(response({ success: true }));
  await settle();
  assert.equal(select.value, '10');
  assert.equal(timers.size, 1);
  assert.equal([...timers.values()][0].ms, 10 * 60 * 1000);
  assert.equal(notices.at(-1).message, 'Course tracking refresh set to 10m.');
  [...timers.values()][0].callback();
  assert.equal(requests.at(-1).url, 'https://example.test/admin/auth/sections/course-tracking');
  requests.at(-1).reject(new Error('Section offline'));
  await settle();
  assert.match(panel.innerHTML, /Section offline/);
  assert.equal(fixture.document.getElementById('admin-auth-overlay').hidden, true);
});

test('term-policy conflict is recoverable and accepted save reaches the actual tracking list refresh receiver once', async () => {
  const fixture = await tracking();
  const { panel, requests, window } = fixture;
  window.initAdminCourseTracking(panel);
  window.initAdminCourseTracking(panel);
  let form = panel.querySelector('[data-term="Fall_2026"]');
  form.elements.state.value = 'open';
  fixture.emit(form, 'submit');
  requests[2].resolve(response({ error: 'Review the changed schedule.', policy: { state: 'closed', effective_state: 'closed', revision: 12 } }, 409));
  await settle();
  form = panel.querySelector('[data-term="Fall_2026"]');
  assert.equal(form.elements.state.value, 'closed');
  assert.equal(form.querySelector('[data-term-notice]').textContent, 'Review the changed schedule.');
  assert.equal(requests.length, 3, 'a conflict does not report a saved policy or reload groups');
  form.elements.state.value = 'open';
  fixture.emit(form.elements.state, 'change');
  fixture.emit(form, 'submit');
  assert.equal(body(requests[3]).expected_revision, 12);
  requests[3].resolve(response({ policy: { state: 'open', effective_state: 'open', revision: 13, polling_enabled: true } }));
  await settle();
  assert.equal(requests.length, 5, 'one policy-saved receiver makes one HTML request');
  assert.equal(requests[4].url, '/admin/auth/sections/course-tracking');
  requests[4].resolve({ ok: true, text: async () => sectionHtml('policy-updated').replace('Resume group', 'Updated group') });
  await settle();
  assert.equal(panel.querySelector('[data-group-toggle]').textContent, 'Updated group');
  assert.equal(panel.querySelector('[data-term="Fall_2026"]').querySelector('[data-term-notice]').textContent, 'Fall 2026 saved. Tracking is open.');
  fixture.emit(panel.querySelector('[data-group-toggle]'), 'click');
  assert.equal(requests.length, 6, 'delegation still handles controls inserted by list-only refresh');
  requests[5].reject(new Error('Keep retry available'));
  await settle();
});

test('auth section caching reinitializes restored tracking controls and forced reload bypasses the cache', async () => {
  const fixture = await tracking();
  const { document, panel, requests, timers } = fixture;
  fixture.emit(document.querySelector('[data-auth-tab="users"]'), 'click');
  assert.match(requests[2].url, /sections\/users\?/);
  requests[2].resolve({ ok: true, text: async () => '<p>Users loaded</p>' });
  await settle();
  fixture.emit(document.querySelector('[data-auth-tab="course-tracking"]'), 'click');
  assert.equal(requests.length, 4, 'cached section restoration only reloads its term data');
  assert.equal(requests[3].url, '/admin/course-tracking/terms');
  requests[3].resolve(response({ terms: [term] }));
  await settle();
  assert.equal(timers.size, 1);
  fixture.emit(document, 'admin-auth:reload-section');
  assert.equal(requests.length, 5);
  await fixture.loadTracking('forced');
  requests[5].resolve(response({ terms: [term] }));
  await settle();
  assert.equal(panel.querySelector('[data-section-version]').dataset.sectionVersion, 'forced');
  assert.equal(new URL(fixture.window.location.href).searchParams.get('tab'), 'course-tracking');
});
